// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCkR_CFs6yyvAks0ZF1ml9TCJIcdVOTI',
    appId: '1:488141518443:web:86d6d881d15f0a7a63a32e',
    messagingSenderId: '488141518443',
    projectId: 'pblparkopsfaiq',
    authDomain: 'pblparkopsfaiq.firebaseapp.com',
    storageBucket: 'pblparkopsfaiq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBwOXmf8TYljZnDcjaC2mTobmwpLHcB7o',
    appId: '1:488141518443:android:b07d0c923b1bc8e863a32e',
    messagingSenderId: '488141518443',
    projectId: 'pblparkopsfaiq',
    storageBucket: 'pblparkopsfaiq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHaTmWP-CxX-B9SB3Scp2QImRDoHXBbFA',
    appId: '1:488141518443:ios:746d5a73bb363e7263a32e',
    messagingSenderId: '488141518443',
    projectId: 'pblparkopsfaiq',
    storageBucket: 'pblparkopsfaiq.firebasestorage.app',
    iosBundleId: 'com.example.pblParkops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHaTmWP-CxX-B9SB3Scp2QImRDoHXBbFA',
    appId: '1:488141518443:ios:746d5a73bb363e7263a32e',
    messagingSenderId: '488141518443',
    projectId: 'pblparkopsfaiq',
    storageBucket: 'pblparkopsfaiq.firebasestorage.app',
    iosBundleId: 'com.example.pblParkops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcCkR_CFs6yyvAks0ZF1ml9TCJIcdVOTI',
    appId: '1:488141518443:web:fbfa4f0857d13b2363a32e',
    messagingSenderId: '488141518443',
    projectId: 'pblparkopsfaiq',
    authDomain: 'pblparkopsfaiq.firebaseapp.com',
    storageBucket: 'pblparkopsfaiq.firebasestorage.app',
  );
}
